apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: default
spec:
  containers:
    - name: docker
      image: docker:latest
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 30; done;"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: trivy
      image: aquasec/trivy:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: workspace
      emptyDir: {}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
