apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: docker
      image: docker:latest
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: trivy
      image: aquasec/trivy:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: workspace
      emptyDir: {}
