apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: jenkins-agent
      image: jenkins/inbound-agent:latest
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
      env:
        - name: HOME
          value: /workspace
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "apt-get update && apt-get install -y git"]
    - name: docker
      image: docker:latest
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 30; done;"
    - name: trivy
      image: aquasec/trivy:latest
      command: ["sleep", "infinity"]
  volumes:
    - name: workspace
      emptyDir: {}
